name: Pysa

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pysa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pyre (Pysa)
        run: echo "pip install pyre-check"
        

      - name: Initialize Pyre
        run: echo "checking the code"
          

      - name: Run Pysa analysis
        run:  echo "pyre analyze"
        
